# Index

GET http://localhost:3000/

# Api

GET http://localhost:3000/smartccivr

# Config

GET http://localhost:3000/smartccivr/config

# Config explain

GET http://localhost:3000/smartccivr/config?path=port

# Start script

POST http://localhost:3000/smartccivr/script/1234/node/start?account_id=0007&application_id=app-id&from=%2B33478597106&to=to-sda&call_id=2234

# Annoucement

POST http://localhost:3000/smartccivr/script/1234/node/1?account_id=0007&call_id=2234

# Annoucement leave
# hangup

POST http://localhost:3000/smartccivr/script/1234/node/1/callback?account_id=0007&call_id=2234

# DTMFCatch

POST http://localhost:3000/smartccivr/script/1234/node/2?account_id=0007&call_id=2234

# DTMFCatch leave retry

POST http://localhost:3000/smartccivr/script/1234/node/2/callback?account_id=0007&call_id=2234&retries=1

# DTMFCatch leave max attempts
# redirect 44

POST http://localhost:3000/smartccivr/script/1234/node/2/callback?account_id=0007&call_id=2234&retries=3

# DTMFCatch leave invalid termdigit
# retry skip first 2 sounds

POST http://localhost:3000/smartccivr/script/1234/node/2/callback?account_id=0007&call_id=2234&retries=2&digits=241&termdigit=1

# DTMFCatch leave invalid numdigits
# retry skip first 2 sounds

POST http://localhost:3000/smartccivr/script/1234/node/2/callback?account_id=0007&call_id=2234&retries=2&digits=24&termdigit=4

# DTMFCatch leave invalid pattern
# retry skip first 2 sounds

POST http://localhost:3000/smartccivr/script/1234/node/2/callback?account_id=0007&call_id=2234&retries=2&digits=254&termdigit=4

# DTMFCatch leave ok
# redirect 43

POST http://localhost:3000/smartccivr/script/1234/node/2/callback?account_id=0007&call_id=2234&retries=2&digits=214&termdigit=4

# Fetch
# redirect 2

POST http://localhost:3000/smartccivr/script/1234/node/3?account_id=0007&call_id=2234

# Fetch leave
# redirect 2

POST http://localhost:3000/smartccivr/script/1234/node/3/callback?account_id=0007&call_id=2234

# Route
# redirect 3 si script/start joue

POST http://localhost:3000/smartccivr/script/1234/node/4?account_id=0007&call_id=2234

# Route leave
# hangup

POST http://localhost:3000/smartccivr/script/1234/node/4/callback?account_id=0007&call_id=2234

# SMTP
# redirect 4

POST http://localhost:3000/smartccivr/script/1234/node/5?account_id=0007&call_id=2234

# SMTP leave
# redirect 4

POST http://localhost:3000/smartccivr/script/1234/node/5/callback?account_id=0007&call_id=2234

# TransferList
# Dial list-sda

POST http://localhost:3000/smartccivr/script/1234/node/6?account_id=0007&call_id=2234&from=from-sda&to=to-sda

# TransferList leave
# Dial list-sda
# envoi des params list a ivrservices

POST http://localhost:3000/smartccivr/script/1234/node/6/callback?account_id=0007&call_id=2234&_dstLst_param1=value1&_dstLst_param2=value2&from=from-sda&to=to-sda

# TransferList leave completed
# Hangup

POST http://localhost:3000/smartccivr/script/1234/node/6/callback?account_id=0007&call_id=2234&_dstLst_param1=value1&_dstLst_param2=value2&dialstatus=completed

# TransferList echec
# Redirect 6

POST http://localhost:3000/smartccivr/script/1234/node/7?account_id=0007&call_id=2234

# TransferQueue
# Playloop queue_waiting

POST http://localhost:3000/smartccivr/script/1234/node/8?account_id=0007&call_id=2234

# TransferQueue leave
# Hangup

POST http://localhost:3000/smartccivr/script/1234/node/8/callback?account_id=0007&call_id=2234

# TransferQueue echec
# Hangup

POST http://localhost:3000/smartccivr/script/1234/node/9?account_id=0007&call_id=2234

# TransferSda
# Dial dest-sda

POST http://localhost:3000/smartccivr/script/1234/node/10?account_id=0007&call_id=2234&from=from-sda&to=to-sda

# TransferSda leave completed
# Hangup

POST http://localhost:3000/smartccivr/script/1234/node/10/callback?account_id=0007&call_id=2234&dialstatus=completed

# TransferSda leave no-answer
# Redirect 42

POST http://localhost:3000/smartccivr/script/1234/node/10/callback?account_id=0007&call_id=2234&dialstatus=no-answer

# TransferSda leave busy
# Redirect 71

POST http://localhost:3000/smartccivr/script/1234/node/10/callback?account_id=0007&call_id=2234&dialstatus=busy

# TransferSda leave other
# Redirect 3

POST http://localhost:3000/smartccivr/script/1234/node/10/callback?account_id=0007&call_id=2234&dialstatus=other

# VoiceRecord
# Record

POST http://localhost:3000/smartccivr/script/1234/node/11?account_id=0007&call_id=2234

# VoiceRecord leave validate
# Redirect 7

POST http://localhost:3000/smartccivr/script/1234/node/11/callback?account_id=0007&call_id=2234&record_url=/record/url

# VoiceRecord leave cancel
# Redirect 4

POST http://localhost:3000/smartccivr/script/1234/node/11/callback?account_id=0007&call_id=2234&record_cause=digit-a&record_digits=23%23&record_url=/record/url

####################################
# Call Context
####################################

GET http://localhost:3000/smartccivr/account/0007/call/2234

####################################
# STATE
####################################
# Created/InProgress

POST http://localhost:3000/smartccivr/script/1234/node/start?account_id=0007&application_id=app-id&from=%2B33478597106&to=to-sda&call_id=2234

# TransferRinging

POST http://localhost:3000/smartccivr/script/1234/node/10?account_id=0007&call_id=2234&from=from-sda&to=to-sda

# <- TransferList leave
# TransferRinging

POST http://localhost:3000/smartccivr/script/1234/node/6/callback?account_id=0007&call_id=2234&_dstLst_param1=value1&_dstLst_param2=value2&from=from-sda&to=to-sda

# <- TransferList enter no-change

POST http://localhost:3000/smartccivr/script/1234/node/7?account_id=0007&call_id=2234

# <- TransferList leave no change

POST http://localhost:3000/smartccivr/script/1234/node/6/callback?account_id=0007&call_id=2234&_dstLst_param1=value1&_dstLst_param2=value2&dialstatus=completed

# Transferred

POST http://localhost:3000/smartccivr/script/1234/dialstatus?account_id=0007&call_id=2234&bridgestatus=in-progress

# AcdTransferred

POST http://localhost:3000/smartccivr/script/1234/node/8?account_id=0007&call_id=2234

# update info.overflow-cause

POST http://localhost:3000/smartccivr/script/1234/node/8/callback?account_id=0007&call_id=2234&overflowcause=NO_AGENT

# update status

POST http://localhost:3000/smartccivr/script/1234/status?account_id=0007&call_id=2234&status=in-progress&cause=hangup-b

# update dial-status FAILED

POST http://localhost:3000/smartccivr/script/1234/dialstatus?account_id=0007&call_id=2234&bridgeduration=42.0&bridgecause=user-hangup&dialstatus=failed&dialcause=hangup-a

# Terminated IVR_HANG_UP

POST http://localhost:3000/smartccivr/script/1234/status?account_id=0007&call_id=2234&status=failed&cause=xml-hangup

# Terminated CALLER_HANG_UP

POST http://localhost:3000/smartccivr/script/1234/status?account_id=0007&call_id=2234&status=failed&cause=user-hangup

####################################
# Geolocalisation
####################################
# +33 number

GET http://localhost:3000/smartccivr/script/1234/node/start?account_id=0007&application_id=app-id&from=%2B33478597106&to=to-sda&call_id=2234

# 06 number

GET http://localhost:3000/smartccivr/script/1234/node/start?account_id=0007&application_id=app-id&from=0666201317&to=to-sda&call_id=2234

# 06 number + paccess

GET http://localhost:3000/smartccivr/script/1234/node/start?account_id=0007&application_id=app-id&from=0666201317&to=to-sda&call_id=2234&siphdr-paccessnetworkinfo=toto-utu%3B%20CP-71600%3B%20titi-cndwq

# unknown

GET http://localhost:3000/smartccivr/script/1234/node/start?account_id=0007&application_id=app-id&from=from-sda&to=to-sda&call_id=2234

# Terminated

POST http://localhost:3000/smartccivr/script/1234/status?account_id=0007&call_id=2234&status=failed&cause=user-hangup
